from decimal import Decimal

from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Sum
from django.urls import reverse
from django.utils.text import slugify

from core.models import Address, Contact, Coordinate
from users.models import User


# =============================================================================
# STATUS (Lookup Table - shared by Site and Project)
# =============================================================================
class Status(models.Model):
    """
    Status lookup table for Projects and Sites.

    Data comes from: Admin panel or seed data.
    Used by: Project and Site models to track workflow state.
    """
    # Active statuses
    STATUS_PROSPECTING = 'prospecting'
    STATUS_PENDING = 'pending_approval'
    STATUS_DELAYED = 'delayed'
    STATUS_STOPPED = 'stopped'
    STATUS_IN_PROGRESS = 'in_progress'
    STATUS_COMPLETED = 'completed'

    # Archived statuses
    STATUS_ARCHIVED_INCLUDED = 'archived_included'
    STATUS_ARCHIVED_EXCLUDED = 'archived_excluded'

    STATUS_CHOICES = [
        (STATUS_PROSPECTING, 'Prospecting'),
        (STATUS_PENDING, 'Pending Approval'),
        (STATUS_DELAYED, 'Delayed/Issue'),
        (STATUS_STOPPED, 'Stopped'),
        (STATUS_IN_PROGRESS, 'In Progress'),
        (STATUS_COMPLETED, 'Completed'),
        (STATUS_ARCHIVED_INCLUDED, 'Archived (Stats Included)'),
        (STATUS_ARCHIVED_EXCLUDED, 'Archived (Stats Excluded)'),
    ]

    code = models.CharField(max_length=30, unique=True, choices=STATUS_CHOICES)
    name = models.CharField(max_length=100)
    emoji = models.CharField(max_length=10)
    is_archived = models.BooleanField(default=False)
    includes_in_carbon = models.BooleanField(default=True)
    display_order = models.IntegerField(default=0)

    class Meta:
        verbose_name_plural = "Statuses"

    def __str__(self):
        return f"{self.emoji} {self.name}"


# =============================================================================
# PROJECT
# =============================================================================
class Project(models.Model):
    # Auto-generated fields that should be disabled in edit forms
    AUTOGENERATED_FIELDS = {
        'area_hectares',  # Calculated from site data
        'total_co2_sequestered_kg',  # Aggregated from sites
        'soil_co2_sequestered_kg',  # Aggregated from sites
        'plant_co2_sequestered_kg',  # Aggregated from sites
        'total_plants',  # Aggregated from sites
        'midpoint_latitude',  # Calculated from site coordinates
        'midpoint_longitude',  # Calculated from site coordinates
        'bounding_box_min_latitude',  # Calculated from site bounding boxes
        'bounding_box_max_latitude',  # Calculated from site bounding boxes
        'bounding_box_min_longitude',  # Calculated from site bounding boxes
        'bounding_box_max_longitude',  # Calculated from site bounding boxes
        'created_at',  # Auto timestamp
        'updated_at',  # Auto timestamp
        'slug',  # Auto-generated from name
    }

    # Project type choices
    PROJECT_TYPE_PRIVATE_LAND = 'private_land'
    PROJECT_TYPE_PUBLIC_LAND = 'public_land'
    PROJECT_TYPE_REFORESTATION = 'reforestation'
    PROJECT_TYPE_URBAN_GREENING = 'urban_greening'
    PROJECT_TYPE_AGROFORESTRY = 'agroforestry'

    PROJECT_TYPE_CHOICES = [
        (PROJECT_TYPE_PRIVATE_LAND, 'Private Land'),
        (PROJECT_TYPE_PUBLIC_LAND, 'Public Land'),
        (PROJECT_TYPE_REFORESTATION, 'Reforestation Project'),
        (PROJECT_TYPE_URBAN_GREENING, 'Urban Greening'),
        (PROJECT_TYPE_AGROFORESTRY, 'Agroforestry'),
    ]

    # Soil type choices
    SOIL_TYPE_CLAY = 'clay'
    SOIL_TYPE_SANDY = 'sandy'
    SOIL_TYPE_SILTY = 'silty'
    SOIL_TYPE_PEATY = 'peaty'
    SOIL_TYPE_CHALKY = 'chalky'
    SOIL_TYPE_LOAMY = 'loamy'
    SOIL_TYPE_MIXED = 'mixed'

    SOIL_TYPE_CHOICES = [
        (SOIL_TYPE_CLAY, 'Clay'),
        (SOIL_TYPE_SANDY, 'Sandy'),
        (SOIL_TYPE_SILTY, 'Silty'),
        (SOIL_TYPE_PEATY, 'Peaty'),
        (SOIL_TYPE_CHALKY, 'Chalky'),
        (SOIL_TYPE_LOAMY, 'Loamy'),
        (SOIL_TYPE_MIXED, 'Mixed'),
    ]

    SOIL_TYPE_DESCRIPTIONS = {
        SOIL_TYPE_CLAY: 'Dense, water-retaining soil. Good for some trees.',
        SOIL_TYPE_SANDY: 'Light, fast-draining soil. Needs more watering.',
        SOIL_TYPE_SILTY: 'Fertile, moisture-retaining soil.',
        SOIL_TYPE_PEATY: 'Acidic, high organic matter. Good for specific species.',
        SOIL_TYPE_CHALKY: 'Alkaline, well-draining. Limited plant selection.',
        SOIL_TYPE_LOAMY: 'Ideal balanced soil for most plants.',
        SOIL_TYPE_MIXED: 'Combination of soil types across the site.',
    }

    # Climate choices
    CLIMATE_TROPICAL = 'tropical'
    CLIMATE_DRY = 'dry'
    CLIMATE_TEMPERATE = 'temperate'
    CLIMATE_CONTINENTAL = 'continental'
    CLIMATE_POLAR = 'polar'
    CLIMATE_MEDITERRANEAN = 'mediterranean'

    CLIMATE_CHOICES = [
        (CLIMATE_TROPICAL, 'Tropical'),
        (CLIMATE_DRY, 'Dry/Arid'),
        (CLIMATE_TEMPERATE, 'Temperate'),
        (CLIMATE_CONTINENTAL, 'Continental'),
        (CLIMATE_POLAR, 'Polar'),
        (CLIMATE_MEDITERRANEAN, 'Mediterranean'),
    ]

    CLIMATE_DESCRIPTIONS = {
        CLIMATE_TROPICAL: 'Hot and humid year-round with high rainfall.',
        CLIMATE_DRY: 'Low rainfall, high evaporation. Drought-resistant species needed.',
        CLIMATE_TEMPERATE: 'Mild temperatures with distinct seasons.',
        CLIMATE_CONTINENTAL: 'Hot summers, cold winters. Wide temperature range.',
        CLIMATE_POLAR: 'Very cold with short growing seasons.',
        CLIMATE_MEDITERRANEAN: 'Warm, dry summers and mild, wet winters.',
    }

    COORDINATE_HELP = (
        "GPS coordinates help us accurately map your project site. "
        "You can find coordinates using Google Maps or GPS devices. "
        "These are optional but recommended for larger projects."
    )

    status = models.ForeignKey(
        Status,
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        related_name='projects'
    )
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True, db_index=True)
    description = models.TextField(null=True, blank=True)
    archived_at = models.DateTimeField(null=True, blank=True)
    address = models.ForeignKey(Address, on_delete=models.PROTECT)
    contact = models.ForeignKey(Contact, on_delete=models.PROTECT)
    coordinates = models.ForeignKey(
        Coordinate,
        on_delete=models.PROTECT,
        null=True,
        blank=True
    )

    # e.g. Private Land, Public Land, Reforestation Project
    project_type = models.CharField(max_length=100, choices=PROJECT_TYPE_CHOICES)

    # e.g. Clay, Sandy, Silty, Peaty, Chalky, Loamy
    soil_type = models.CharField(max_length=50, choices=SOIL_TYPE_CHOICES)

    # e.g. Tropical, Dry, Temperate, Continental, Polar
    climate = models.CharField(max_length=50, choices=CLIMATE_CHOICES)
    area_hectares = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        null=True,
        blank=True
    )  # Calculated/updated later from site data

    # Aggregated carbon metrics (summed from all sites in this project)
    total_co2_sequestered_kg = models.BigIntegerField(null=True, blank=True)
    soil_co2_sequestered_kg = models.BigIntegerField(null=True, blank=True)
    plant_co2_sequestered_kg = models.BigIntegerField(null=True, blank=True)
    total_plants = models.IntegerField(null=True, blank=True)

    # Midpoint coordinate (calculated from all site polygon coordinates)
    midpoint_latitude = models.DecimalField(
        max_digits=10,
        decimal_places=7,
        null=True,
        blank=True
    )
    midpoint_longitude = models.DecimalField(
        max_digits=11,
        decimal_places=7,
        null=True,
        blank=True
    )

    # Bounding box (calculated from all site bounding boxes - for map centering)
    bounding_box_min_latitude = models.DecimalField(
        max_digits=10,
        decimal_places=7,
        null=True,
        blank=True
    )
    bounding_box_max_latitude = models.DecimalField(
        max_digits=10,
        decimal_places=7,
        null=True,
        blank=True
    )
    bounding_box_min_longitude = models.DecimalField(
        max_digits=11,
        decimal_places=7,
        null=True,
        blank=True
    )
    bounding_box_max_longitude = models.DecimalField(
        max_digits=11,
        decimal_places=7,
        null=True,
        blank=True
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(User, on_delete=models.PROTECT, null=True, blank=True, related_name='created_projects')

    def calculate_midpoint_from_sites(self):
        """
        Calculate and update the midpoint coordinate based on all site polygon coordinates.
        Uses the center of each site's bounding box or polygon (whichever is available).
        Returns the calculated (latitude, longitude) tuple or (None, None) if no sites have coordinates.
        """
        all_latitudes = []
        all_longitudes = []

        for site in self.sites.all():
            geojson = site.bounding_box_coordinates

            if geojson and isinstance(geojson, dict) and 'coordinates' in geojson:
                coordinates = geojson['coordinates'][0]
                for coord in coordinates:
                    if isinstance(coord, (list, tuple)) and len(coord) >= 2:
                        all_longitudes.append(Decimal(str(coord[0])))
                        all_latitudes.append(Decimal(str(coord[1])))

        if all_latitudes and all_longitudes:
            self.midpoint_latitude = sum(all_latitudes) / len(all_latitudes)
            self.midpoint_longitude = sum(all_longitudes) / len(all_longitudes)
            self.save(update_fields=['midpoint_latitude', 'midpoint_longitude'])
            return (self.midpoint_latitude, self.midpoint_longitude)

        return (None, None)

    def calculate_bounding_box_from_sites(self):
        """
        Calculate and update the project bounding box from all site bounding boxes.
        Uses max extents of all sites for map centering.
        """
        all_lats = []
        all_lngs = []

        for site in self.sites.all():
            geojson = site.bounding_box_coordinates

            if geojson and isinstance(geojson, dict) and 'coordinates' in geojson:
                coordinates = geojson['coordinates'][0]
                for coord in coordinates:
                    if isinstance(coord, (list, tuple)) and len(coord) >= 2:
                        all_lngs.append(Decimal(str(coord[0])))
                        all_lats.append(Decimal(str(coord[1])))

        if all_lats and all_lngs:
            self.bounding_box_min_latitude = min(all_lats)
            self.bounding_box_max_latitude = max(all_lats)
            self.bounding_box_min_longitude = min(all_lngs)
            self.bounding_box_max_longitude = max(all_lngs)
            self.save(update_fields=[
                'bounding_box_min_latitude', 'bounding_box_max_latitude',
                'bounding_box_min_longitude', 'bounding_box_max_longitude'
            ])
            return (
                self.bounding_box_min_latitude, self.bounding_box_max_latitude,
                self.bounding_box_min_longitude, self.bounding_box_max_longitude
            )

        return (None, None, None, None)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)

        # On save, recalculate midpoint and bounding box
        super().save(*args, **kwargs)
        self.calculate_midpoint_from_sites()
        self.calculate_bounding_box_from_sites()

    def __str__(self):
        return self.name

    def get_card_groups(self):
        """
        Returns card group data for project planner display.

        Cards are structured to match wizard forms 1:1 for consistent UX:
        - Card fields = Form fields (what you see is what you can edit)
        - edit_form references the form class name (step is resolved automatically)

        The edit_form value is the form class name (e.g., 'ProjectBasicInfoForm').
        render_card_groups() will resolve this to a step number using the wizard.

        Returns:
            List of dicts with keys: title, icon, fields (or sections),
            and optional edit_form (form class name for editing)
        """
        # Get display labels for choice fields
        project_type_display = dict(self.PROJECT_TYPE_CHOICES).get(
            self.project_type, self.project_type
        ) or 'N/A'
        soil_type_display = dict(self.SOIL_TYPE_CHOICES).get(
            self.soil_type, self.soil_type
        ) or 'N/A'
        climate_display = dict(self.CLIMATE_CHOICES).get(
            self.climate, self.climate
        ) or 'N/A'

        return [
            {
                'title': 'Basic Info',
                'icon': 'bi bi-folder',
                'edit_form': 'ProjectBasicInfoForm',
                'fields': [
                    ('Project Name', self.name or 'N/A'),
                    ('Project Type', project_type_display),
                    ('Status', str(self.status) if self.status else 'N/A'),
                    ('Description', self.description or '—'),
                ],
            },
            {
                'title': 'Environment',
                'icon': 'bi bi-tree',
                'edit_form': 'ProjectEnvironmentForm',
                'fields': [
                    ('Soil Type', soil_type_display),
                    ('Climate', climate_display),
                    ('Area (hectares)', f"{self.area_hectares}" if self.area_hectares else 'Not calculated'),
                ],
            },
            {
                'title': 'Address',
                'icon': 'bi bi-geo-alt',
                'edit_form': 'ProjectAddressForm',
                'fields': [
                    ('Address Line 1', self.address.address_line_1 or 'N/A' if self.address else 'N/A'),
                    ('Address Line 2', self.address.address_line_2 or '—' if self.address else '—'),
                    ('City', self.address.city or 'N/A' if self.address else 'N/A'),
                    ('Region', self.address.region or '—' if self.address else '—'),
                    ('Postcode', self.address.postcode or 'N/A' if self.address else 'N/A'),
                    ('Country', str(self.address.country_code) if self.address and self.address.country_code else 'N/A'),
                ],
            },
            {
                'title': 'Coordinates',
                'icon': 'bi bi-pin-map',
                'edit_form': 'ProjectCoordinatesForm',
                'fields': [
                    ('Latitude', str(self.coordinates.latitude) if self.coordinates and self.coordinates.latitude else '—'),
                    ('Longitude', str(self.coordinates.longitude) if self.coordinates and self.coordinates.longitude else '—'),
                    ('Altitude (m)', str(self.coordinates.altitude) if self.coordinates and self.coordinates.altitude else '—'),
                    ('Elevation (m)', str(self.coordinates.elevation) if self.coordinates and self.coordinates.elevation else '—'),
                    ('Coordinate System', self.coordinates.coordinate_system if self.coordinates and self.coordinates.coordinate_system else '—'),
                    ('What3Words', self.coordinates.what3w if self.coordinates and self.coordinates.what3w else '—'),
                ],
            },
            {
                'title': 'Contact Information',
                'icon': 'bi bi-people',
                'edit_form': 'ProjectContactForm',
                'sections': [
                    {
                        'title': 'Company',
                        'fields': [
                            ('Name', self.contact.company_name or '—' if self.contact else '—'),
                            ('Email', self.contact.company_email or '—' if self.contact else '—'),
                            ('Phone', self.contact.company_phone or '—' if self.contact else '—'),
                            ('Website', self.contact.company_website or '—' if self.contact else '—'),
                        ],
                    },
                    {
                        'title': 'Primary Contact',
                        'fields': [
                            ('Title/Role', self.contact.primary_contact_title or '—' if self.contact else '—'),
                            ('Name', self.contact.primary_contact_name or '—' if self.contact else '—'),
                            ('Pronouns', self.contact.primary_contact_pronouns or '—' if self.contact else '—'),
                            ('Email', self.contact.primary_contact_email or '—' if self.contact else '—'),
                            ('Phone', self.contact.primary_contact_phone or '—' if self.contact else '—'),
                        ],
                    },
                    {
                        'title': 'Land Owner',
                        'fields': [
                            ('Title/Role', self.contact.land_owner_title or '—' if self.contact else '—'),
                            ('Name', self.contact.land_owner_name or '—' if self.contact else '—'),
                            ('Pronouns', self.contact.land_owner_pronouns or '—' if self.contact else '—'),
                            ('Email', self.contact.land_owner_email or '—' if self.contact else '—'),
                            ('Phone', self.contact.land_owner_phone or '—' if self.contact else '—'),
                            ('Organization', self.contact.land_owner_organization or '—' if self.contact else '—'),
                            ('Preferred Contact', self.contact.land_owner_preferred_contact_method or '—' if self.contact else '—'),
                        ],
                    },
                    {
                        'title': 'Secondary Contact',
                        'fields': [
                            ('Title/Role', self.contact.secondary_contact_title or '—' if self.contact else '—'),
                            ('Name', self.contact.secondary_contact_name or '—' if self.contact else '—'),
                            ('Pronouns', self.contact.secondary_contact_pronouns or '—' if self.contact else '—'),
                            ('Email', self.contact.secondary_contact_email or '—' if self.contact else '—'),
                            ('Phone', self.contact.secondary_contact_phone or '—' if self.contact else '—'),
                        ],
                    },
                    {
                        'title': 'Notes',
                        'fields': [
                            ('Notes', self.contact.notes or '—' if self.contact else '—'),
                        ],
                    },
                ],
            },
        ]

    def get_absolute_url(self):
        return reverse('projects:project_detail', kwargs={'slug': self.slug})


# =============================================================================
# SITE
# =============================================================================
class Site(models.Model):
    project = models.ForeignKey(Project, on_delete=models.PROTECT, related_name='sites')
    status = models.ForeignKey(
        Status,
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        related_name='sites'
    )
    name = models.CharField(max_length=255, db_index=True)
    description = models.TextField(null=True, blank=True)
    archived_at = models.DateTimeField(null=True, blank=True)
    est_completion_date = models.DateTimeField()
    completion_percentage = models.IntegerField()
    maturity_years = models.IntegerField()
    current_year = models.IntegerField()
    total_plants = models.IntegerField()
    total_available_land_hectares = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        null=True,
        blank=True
    )
    land_utilised_percentage = models.IntegerField(null=True, blank=True)
    avg_health_index = models.DecimalField(max_digits=4, decimal_places=2, null=True, blank=True)
    total_co2_sequestered_kg = models.BigIntegerField(null=True, blank=True)
    soil_co2_sequestered_kg = models.BigIntegerField(null=True, blank=True)
    plant_co2_sequestered_kg = models.BigIntegerField(null=True, blank=True)
    average_plant_height_m = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        null=True,
        blank=True
    )

    # Biodiversity tracking
    biodiversity_index = models.DecimalField(
        max_digits=6,
        decimal_places=2,
        null=True,
        blank=True
    )
    biodiversity_last_calculated = models.DateTimeField(null=True, blank=True)

    # Site boundary (GeoJSON Polygon — the overall site bounds set at creation)
    bounding_box_coordinates = models.JSONField(default=dict, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.name}"


# =============================================================================
# COMPONENT FOLDER (Outliner organization — visibility/lock toggle for children)
# =============================================================================
class ComponentFolder(models.Model):
    """
    Organizational folder in the outliner tree.
    Toggles visibility/lock for all child components.
    Does not affect transform — purely for organization.
    """
    site = models.ForeignKey(Site, on_delete=models.CASCADE, related_name='component_folders')
    name = models.CharField(max_length=255, default='New Folder')
    parent = models.ForeignKey(
        'self',
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name='children'
    )
    expanded = models.BooleanField(default=True)
    visible = models.BooleanField(default=True)
    locked = models.BooleanField(default=False)
    z_order = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['z_order', 'created_at']

    def __str__(self):
        return self.name


# =============================================================================
# MAP COMPONENT (Vector shapes on the map — polygons, lines, points)
# =============================================================================
class MapComponent(models.Model):
    """
    A vector component on the map: polygon, polyline, or point.
    Stores geometry as strict GeoJSON (RFC 7946) for MapLibre compatibility
    and lossless GeoPackage conversion.
    """
    GEOMETRY_TYPES = [
        ('Polygon', 'Polygon'),
        ('MultiPolygon', 'MultiPolygon'),
        ('LineString', 'LineString'),
        ('MultiLineString', 'MultiLineString'),
        ('Point', 'Point'),
        ('MultiPoint', 'MultiPoint'),
    ]
    DATA_TYPES = [
        ('annotation', 'Annotation'),
        ('inclusion', 'Inclusion Zone'),
        ('exclusion', 'Exclusion Zone'),
    ]
    FILL_PATTERNS = [
        ('solid', 'Solid'),
        ('hatched', 'Hatched'),
        ('dotted', 'Dotted'),
        ('none', 'None / Outline Only'),
    ]

    site = models.ForeignKey(Site, on_delete=models.CASCADE, related_name='map_components')
    folder = models.ForeignKey(
        ComponentFolder,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='components'
    )
    name = models.CharField(max_length=255, default='Untitled')

    # GeoJSON geometry — strict RFC 7946 format
    # Example: {"type": "Polygon", "coordinates": [[[lng, lat], ...]]}
    geometry_type = models.CharField(max_length=20, choices=GEOMETRY_TYPES)
    geometry = models.JSONField()

    # Data type — behavioral classification
    data_type = models.CharField(max_length=20, choices=DATA_TYPES, default='annotation')

    # Visual properties
    stroke_color = models.CharField(max_length=9, default='#3388ff')
    fill_color = models.CharField(max_length=9, default='#3388ff')
    fill_opacity = models.FloatField(default=0.3)
    stroke_width = models.FloatField(default=2.0)
    fill_pattern = models.CharField(max_length=20, choices=FILL_PATTERNS, default='solid')

    # Parametric metadata (e.g. {"sides": 6, "radius": 50} for hexagon)
    parametric = models.JSONField(default=dict, blank=True)

    # Display
    visible = models.BooleanField(default=True)
    locked = models.BooleanField(default=False)
    z_order = models.IntegerField(default=0)

    # Annotation-specific fields
    annotation_title = models.CharField(max_length=255, blank=True)
    annotation_description = models.TextField(blank=True)
    annotation_icon = models.CharField(max_length=50, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['z_order', 'created_at']
        indexes = [
            models.Index(fields=['site', 'geometry_type']),
            models.Index(fields=['site', 'data_type']),
            models.Index(fields=['site', 'folder']),
        ]

    def __str__(self):
        return f"{self.name} ({self.geometry_type})"

    def clean(self):
        """Validate geometry using Shapely."""
        from shapely.geometry import shape as shapely_shape
        try:
            geom = shapely_shape(self.geometry)
            if not geom.is_valid:
                raise ValidationError({'geometry': 'Invalid geometry — self-intersecting or malformed.'})
        except ValidationError:
            raise
        except Exception as e:
            raise ValidationError({'geometry': f'Geometry validation failed: {e}'})

    def to_geojson_feature(self):
        """Serialize to a GeoJSON Feature dict."""
        return {
            'type': 'Feature',
            'id': self.pk,
            'geometry': self.geometry,
            'properties': {
                'name': self.name,
                'data_type': self.data_type,
                'stroke_color': self.stroke_color,
                'fill_color': self.fill_color,
                'fill_opacity': self.fill_opacity,
                'stroke_width': self.stroke_width,
                'fill_pattern': self.fill_pattern,
                'parametric': self.parametric,
                'visible': self.visible,
                'locked': self.locked,
                'z_order': self.z_order,
                'folder_id': self.folder_id,
                'annotation_title': self.annotation_title,
                'annotation_description': self.annotation_description,
                'annotation_icon': self.annotation_icon,
            },
        }


# =============================================================================
# HELPER METHODS FOR AGGREGATION
# =============================================================================

def update_project_totals_from_sites(project):
    """
    Update Project totals by aggregating from all Site records.
    Call this after updating site totals.
    """
    # Aggregate carbon data from all sites in this project
    site_aggregates = project.sites.aggregate(
        total_co2=Sum('total_co2_sequestered_kg'),
        soil_co2=Sum('soil_co2_sequestered_kg'),
        plant_co2=Sum('plant_co2_sequestered_kg'),
        total_plants=Sum('total_plants'),
    )

    # Update project totals
    project.total_co2_sequestered_kg = site_aggregates['total_co2'] or 0
    project.soil_co2_sequestered_kg = site_aggregates['soil_co2'] or 0
    project.plant_co2_sequestered_kg = site_aggregates['plant_co2'] or 0
    project.total_plants = site_aggregates['total_plants'] or 0

    project.save(update_fields=[
        'total_co2_sequestered_kg',
        'soil_co2_sequestered_kg',
        'plant_co2_sequestered_kg',
        'total_plants'
    ])
