# Generated by Django 5.1.15 on 2026-01-15 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_setup_complete',
            field=models.BooleanField(default=False, help_text='Whether user has completed the profile setup wizard'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pronouns',
            field=models.CharField(blank=True, choices=[('', 'Prefer not to say'), ('he/him', 'He/Him'), ('she/her', 'She/Her'), ('they/them', 'They/Them'), ('other', 'Other')], max_length=20),
        ),
    ]
