# Generated by Django 5.1.15 on 2026-01-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme_mode',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='dark', help_text='Light/Dark mode preference', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('default', 'Default'), ('moon', 'Moon'), ('gaia', 'Gaia'), ('sunset', 'Sunset'), ('honeycomb', 'Honeycomb')], default='default', help_text='Color theme selection', max_length=20),
        ),
    ]
