# Generated by Django 5.1.15 on 2026-01-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_theme_mode_alter_user_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('default', 'Default'), ('moon', 'Moon'), ('gaia', 'Gaia'), ('sunset', 'Sunset'), ('honeycomb', 'Honeycomb'), ('ocean', 'Ocean')], default='default', help_text='Color theme selection', max_length=20),
        ),
    ]
