# Generated by Django 5.1.15 on 2026-01-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_profile_setup_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='theme_mode',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='system', help_text='Light/Dark mode preference', max_length=10),
        ),
    ]
