# Generated by Django 5.1.15 on 2026-03-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_sixlabs_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('default', 'Default'), ('moon', 'Moon'), ('gaia', 'Gaia'), ('sunset', 'Sunset'), ('honeycomb', 'Honeycomb'), ('ocean', 'Ocean'), ('6xlabs', '6xLabs')], default='default', help_text='Color theme selection', max_length=20),
        ),
    ]
