# Generated by Django 5.1.15 on 2026-01-05 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('drones', '0001_initial'),
        ('seed_catalogue', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('project_type', models.CharField(max_length=100)),
                ('soil_type', models.CharField(max_length=50)),
                ('climate', models.CharField(max_length=50)),
                ('area_hectares', models.DecimalField(decimal_places=2, max_digits=10)),
                ('midpoint_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('midpoint_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True)),
                ('bounding_box_min_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('bounding_box_max_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('bounding_box_min_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True)),
                ('bounding_box_max_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.address')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.contact')),
                ('coordinates', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.coordinate')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='core.status')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('est_completion_date', models.DateTimeField()),
                ('completion_percentage', models.IntegerField()),
                ('maturity_years', models.IntegerField()),
                ('current_year', models.IntegerField()),
                ('total_plants', models.IntegerField()),
                ('total_available_land_hectares', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('land_utilised_percentage', models.IntegerField(blank=True, null=True)),
                ('avg_health_index', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('total_co2_sequestered_kg', models.BigIntegerField(blank=True, null=True)),
                ('soil_co2_sequestered_kg', models.BigIntegerField(blank=True, null=True)),
                ('plant_co2_sequestered_kg', models.BigIntegerField(blank=True, null=True)),
                ('average_plant_height_m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('biodiversity_index', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('biodiversity_last_calculated', models.DateTimeField(blank=True, null=True)),
                ('bounding_box_coordinates', models.JSONField(blank=True, default=dict)),
                ('site_boundary_polygon', models.JSONField(blank=True, default=dict)),
                ('site_exclusion_polygons', models.JSONField(blank=True, default=dict)),
                ('entrance_pathfinding', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='projects.project')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='core.status')),
            ],
        ),
        migrations.CreateModel(
            name='SeedBatchUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used_g', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seeds_planted_estimate', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('seed_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='seed_catalogue.seedbatch')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seed_usages', to='projects.site')),
            ],
        ),
        migrations.CreateModel(
            name='PlantingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_code', models.IntegerField(db_index=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('zone_boundary_polygon', models.JSONField()),
                ('active', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planting_zones', to='projects.site')),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_planted', models.DateField(blank=True, db_index=True, null=True)),
                ('latitude', models.DecimalField(db_index=True, decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(db_index=True, decimal_places=7, max_digits=11)),
                ('altitude', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('elevation', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('queue_order', models.IntegerField(blank=True, db_index=True, null=True)),
                ('current_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plants', to='core.plantstatus')),
                ('original_plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replants', to='projects.plant')),
                ('seed_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plants', to='seed_catalogue.seedbatch')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plants', to='core.species')),
                ('planting_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plants', to='projects.plantingzone')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plants', to='projects.site')),
            ],
        ),
        migrations.CreateModel(
            name='FungiBatchUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_used_grams', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_used_ml', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('fungi_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='seed_catalogue.fungibatch')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fungi_usages', to='projects.site')),
            ],
        ),
        migrations.CreateModel(
            name='SiteNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.user')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='projects.site')),
            ],
        ),
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_type', models.CharField(choices=[('planting', 'Planting'), ('prospecting', 'Prospecting'), ('inspection', 'Inspection')], default='prospecting', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('plants_checked', models.IntegerField(default=0)),
                ('plants_alive', models.IntegerField(default=0)),
                ('plants_dead', models.IntegerField(default=0)),
                ('fungi_applied', models.IntegerField(default=0)),
                ('total_co2_sequestered_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('avg_health_index', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('avg_plant_height_m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('avg_canopy_width_m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('avg_soil_moisture', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('assigned_drone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='site_visits', to='drones.drone')),
                ('pilot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='piloted_visits', to='users.user')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='projects.site')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PlantVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('health_index', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('canopy_width_m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('soil_moisture_level', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('co2_sequestered_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('photo_evidence', models.JSONField(blank=True, default=list)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='projects.plant')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.plantstatus')),
                ('site_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_visits', to='projects.sitevisit')),
            ],
        ),
        migrations.CreateModel(
            name='FungiVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ml', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fungi_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fungi_visits', to='seed_catalogue.fungibatch')),
                ('fungi_species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.species')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fungi_visits', to='projects.plant')),
                ('site_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fungi_visits', to='projects.sitevisit')),
            ],
        ),
        migrations.CreateModel(
            name='SiteVisitContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('pilot', 'Drone Pilot'), ('technician', 'Technician'), ('guest', 'Guest')], max_length=50)),
                ('guest_name', models.CharField(blank=True, max_length=255, null=True)),
                ('guest_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('guest_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('guest_organization', models.CharField(blank=True, max_length=255, null=True)),
                ('site_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='projects.sitevisit')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='site_visit_participations', to='users.user')),
            ],
        ),
        migrations.AddIndex(
            model_name='plantingzone',
            index=models.Index(fields=['site', 'active'], name='projects_pl_site_id_b1a85f_idx'),
        ),
        migrations.AddIndex(
            model_name='plantingzone',
            index=models.Index(fields=['site', 'zone_code'], name='projects_pl_site_id_08df8a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='plantingzone',
            unique_together={('site', 'zone_code')},
        ),
        migrations.AddIndex(
            model_name='plant',
            index=models.Index(fields=['site', 'current_status'], name='projects_pl_site_id_faf59b_idx'),
        ),
        migrations.AddIndex(
            model_name='plant',
            index=models.Index(fields=['site', 'queue_order'], name='projects_pl_site_id_67457f_idx'),
        ),
        migrations.AddIndex(
            model_name='plant',
            index=models.Index(fields=['planting_zone', 'current_status'], name='projects_pl_plantin_a411fa_idx'),
        ),
        migrations.AddIndex(
            model_name='sitevisit',
            index=models.Index(fields=['site', 'timestamp'], name='projects_si_site_id_206298_idx'),
        ),
        migrations.AddIndex(
            model_name='sitevisit',
            index=models.Index(fields=['pilot', 'timestamp'], name='projects_si_pilot_i_5760ff_idx'),
        ),
        migrations.AddIndex(
            model_name='plantvisit',
            index=models.Index(fields=['site_visit', 'plant'], name='projects_pl_site_vi_33a26f_idx'),
        ),
        migrations.AddIndex(
            model_name='plantvisit',
            index=models.Index(fields=['site_visit', 'status'], name='projects_pl_site_vi_4402e7_idx'),
        ),
        migrations.AddIndex(
            model_name='sitevisitcontributor',
            index=models.Index(fields=['site_visit', 'role'], name='projects_si_site_vi_6be686_idx'),
        ),
        migrations.AddIndex(
            model_name='sitevisitcontributor',
            index=models.Index(fields=['user'], name='projects_si_user_id_162bae_idx'),
        ),
    ]
