# Generated by Django 5.1.15 on 2026-01-12 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('prospecting', 'Prospecting'), ('pending_approval', 'Pending Approval'), ('delayed', 'Delayed/Issue'), ('stopped', 'Stopped'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('archived_included', 'Archived (Stats Included)'), ('archived_excluded', 'Archived (Stats Excluded)')], max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('emoji', models.CharField(max_length=10)),
                ('is_archived', models.BooleanField(default=False)),
                ('includes_in_carbon', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Statuses',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('project_type', models.CharField(max_length=100)),
                ('soil_type', models.CharField(max_length=50)),
                ('climate', models.CharField(max_length=50)),
                ('area_hectares', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_co2_sequestered_kg', models.BigIntegerField(blank=True, null=True)),
                ('soil_co2_sequestered_kg', models.BigIntegerField(blank=True, null=True)),
                ('plant_co2_sequestered_kg', models.BigIntegerField(blank=True, null=True)),
                ('total_plants', models.IntegerField(blank=True, null=True)),
                ('midpoint_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('midpoint_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True)),
                ('bounding_box_min_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('bounding_box_max_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('bounding_box_min_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True)),
                ('bounding_box_max_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.address')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.contact')),
                ('coordinates', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.coordinate')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('est_completion_date', models.DateTimeField()),
                ('completion_percentage', models.IntegerField()),
                ('maturity_years', models.IntegerField()),
                ('current_year', models.IntegerField()),
                ('total_plants', models.IntegerField()),
                ('total_available_land_hectares', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('land_utilised_percentage', models.IntegerField(blank=True, null=True)),
                ('avg_health_index', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('total_co2_sequestered_kg', models.BigIntegerField(blank=True, null=True)),
                ('soil_co2_sequestered_kg', models.BigIntegerField(blank=True, null=True)),
                ('plant_co2_sequestered_kg', models.BigIntegerField(blank=True, null=True)),
                ('average_plant_height_m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('biodiversity_index', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('biodiversity_last_calculated', models.DateTimeField(blank=True, null=True)),
                ('bounding_box_coordinates', models.JSONField(blank=True, default=dict)),
                ('site_boundary_polygon', models.JSONField(blank=True, default=dict)),
                ('site_exclusion_polygons', models.JSONField(blank=True, default=dict)),
                ('entrance_pathfinding', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='projects.project')),
            ],
        ),
    ]
