# Generated by Django 5.1.15 on 2026-01-12 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drones', '0003_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sitenote',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sitenote',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='projects.site'),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='assigned_drone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='site_visits', to='drones.drone'),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='pilot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='piloted_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='projects.site'),
        ),
        migrations.AddField(
            model_name='plantvisit',
            name='site_visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_visits', to='projects.sitevisit'),
        ),
        migrations.AddField(
            model_name='fungivisit',
            name='site_visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fungi_visits', to='projects.sitevisit'),
        ),
        migrations.AddField(
            model_name='sitevisitcontributor',
            name='site_visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='projects.sitevisit'),
        ),
        migrations.AddField(
            model_name='sitevisitcontributor',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='site_visit_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='site',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='projects.status'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.status'),
        ),
        migrations.AddIndex(
            model_name='plantingzone',
            index=models.Index(fields=['site', 'active'], name='projects_pl_site_id_b1a85f_idx'),
        ),
        migrations.AddIndex(
            model_name='plantingzone',
            index=models.Index(fields=['site', 'zone_code'], name='projects_pl_site_id_08df8a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='plantingzone',
            unique_together={('site', 'zone_code')},
        ),
        migrations.AddIndex(
            model_name='plant',
            index=models.Index(fields=['site', 'current_status'], name='projects_pl_site_id_faf59b_idx'),
        ),
        migrations.AddIndex(
            model_name='plant',
            index=models.Index(fields=['site', 'queue_order'], name='projects_pl_site_id_67457f_idx'),
        ),
        migrations.AddIndex(
            model_name='plant',
            index=models.Index(fields=['planting_zone', 'current_status'], name='projects_pl_plantin_a411fa_idx'),
        ),
        migrations.AddIndex(
            model_name='sitevisit',
            index=models.Index(fields=['site', 'timestamp'], name='projects_si_site_id_206298_idx'),
        ),
        migrations.AddIndex(
            model_name='sitevisit',
            index=models.Index(fields=['pilot', 'timestamp'], name='projects_si_pilot_i_5760ff_idx'),
        ),
        migrations.AddIndex(
            model_name='plantvisit',
            index=models.Index(fields=['site_visit', 'plant'], name='projects_pl_site_vi_33a26f_idx'),
        ),
        migrations.AddIndex(
            model_name='plantvisit',
            index=models.Index(fields=['site_visit', 'status'], name='projects_pl_site_vi_4402e7_idx'),
        ),
        migrations.AddIndex(
            model_name='sitevisitcontributor',
            index=models.Index(fields=['site_visit', 'role'], name='projects_si_site_vi_6be686_idx'),
        ),
        migrations.AddIndex(
            model_name='sitevisitcontributor',
            index=models.Index(fields=['user'], name='projects_si_user_id_162bae_idx'),
        ),
    ]
