# Generated by Django 5.1.15 on 2026-01-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='plant_co2_sequestered_kg',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='soil_co2_sequestered_kg',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='total_co2_sequestered_kg',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='total_plants',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
