# Generated by Django 5.1.15 on 2026-01-16 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='climate',
            field=models.CharField(choices=[('tropical', 'Tropical'), ('dry', 'Dry/Arid'), ('temperate', 'Temperate'), ('continental', 'Continental'), ('polar', 'Polar'), ('mediterranean', 'Mediterranean')], max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('private_land', 'Private Land'), ('public_land', 'Public Land'), ('reforestation', 'Reforestation Project'), ('urban_greening', 'Urban Greening'), ('agroforestry', 'Agroforestry')], max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='soil_type',
            field=models.CharField(choices=[('clay', 'Clay'), ('sandy', 'Sandy'), ('silty', 'Silty'), ('peaty', 'Peaty'), ('chalky', 'Chalky'), ('loamy', 'Loamy'), ('mixed', 'Mixed')], max_length=50),
        ),
    ]
