# Generated by Django 5.1.15 on 2026-01-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_created_by_alter_project_climate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='site_boundary_polygon',
            field=models.JSONField(blank=True, db_column='site_boundary_polygon', default=dict),
        ),
        migrations.RenameField(
            model_name='site',
            old_name='site_boundary_polygon',
            new_name='site_inclusion_polygons',
        ),
    ]
