# Generated by Django 5.1.15 on 2026-02-08 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_site_site_boundary_polygon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='entrance_pathfinding',
        ),
        migrations.RemoveField(
            model_name='site',
            name='site_exclusion_polygons',
        ),
        migrations.RemoveField(
            model_name='site',
            name='site_inclusion_polygons',
        ),
        migrations.CreateModel(
            name='ComponentFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Folder', max_length=255)),
                ('expanded', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=True)),
                ('locked', models.BooleanField(default=False)),
                ('z_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='projects.componentfolder')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_folders', to='projects.site')),
            ],
            options={
                'ordering': ['z_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MapComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled', max_length=255)),
                ('geometry_type', models.CharField(choices=[('Polygon', 'Polygon'), ('MultiPolygon', 'MultiPolygon'), ('LineString', 'LineString'), ('MultiLineString', 'MultiLineString'), ('Point', 'Point'), ('MultiPoint', 'MultiPoint')], max_length=20)),
                ('geometry', models.JSONField()),
                ('data_type', models.CharField(choices=[('annotation', 'Annotation'), ('inclusion', 'Inclusion Zone'), ('exclusion', 'Exclusion Zone')], default='annotation', max_length=20)),
                ('stroke_color', models.CharField(default='#3388ff', max_length=9)),
                ('fill_color', models.CharField(default='#3388ff', max_length=9)),
                ('fill_opacity', models.FloatField(default=0.3)),
                ('stroke_width', models.FloatField(default=2.0)),
                ('fill_pattern', models.CharField(choices=[('solid', 'Solid'), ('hatched', 'Hatched'), ('dotted', 'Dotted'), ('none', 'None / Outline Only')], default='solid', max_length=20)),
                ('parametric', models.JSONField(blank=True, default=dict)),
                ('visible', models.BooleanField(default=True)),
                ('locked', models.BooleanField(default=False)),
                ('z_order', models.IntegerField(default=0)),
                ('annotation_title', models.CharField(blank=True, max_length=255)),
                ('annotation_description', models.TextField(blank=True)),
                ('annotation_icon', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='projects.componentfolder')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_components', to='projects.site')),
            ],
            options={
                'ordering': ['z_order', 'created_at'],
                'indexes': [models.Index(fields=['site', 'geometry_type'], name='projects_ma_site_id_950c15_idx'), models.Index(fields=['site', 'data_type'], name='projects_ma_site_id_0ea07a_idx'), models.Index(fields=['site', 'folder'], name='projects_ma_site_id_140cdd_idx')],
            },
        ),
    ]
