# Generated by Django 5.1.15 on 2026-01-12 13:35

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('postcode', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('country_code', django_countries.fields.CountryField(blank=True, db_index=True, max_length=2, null=True)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('company_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('company_website', models.URLField(blank=True, max_length=255, null=True)),
                ('primary_contact_title', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_contact_pronouns', models.CharField(blank=True, max_length=20, null=True)),
                ('primary_contact_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('primary_contact_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('secondary_contact_title', models.CharField(blank=True, max_length=100, null=True)),
                ('secondary_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('secondary_contact_pronouns', models.CharField(blank=True, max_length=20, null=True)),
                ('secondary_contact_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('secondary_contact_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('land_owner_title', models.CharField(blank=True, max_length=100, null=True)),
                ('land_owner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('land_owner_pronouns', models.CharField(blank=True, max_length=20, null=True)),
                ('land_owner_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('land_owner_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('land_owner_organization', models.CharField(blank=True, max_length=255, null=True)),
                ('land_owner_preferred_contact_method', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(db_index=True, decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(db_index=True, decimal_places=7, max_digits=11)),
                ('altitude', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('elevation', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('coordinate_system', models.CharField(default='WGS84', max_length=20)),
                ('what3w', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.SlugField(max_length=100, unique=True)),
                ('item_type', models.CharField(choices=[('profile', 'Profile'), ('modal', 'Modal Trigger'), ('link', 'Link'), ('parent', 'Parent (has children)')], default='link', max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('icon', models.CharField(help_text='Bootstrap icon class or image path', max_length=100)),
                ('url_name', models.CharField(blank=True, help_text="Django URL name (e.g., 'projects:project_planner') or path", max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text="False = 'Coming Soon'")),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('staff_only', models.BooleanField(default=False, help_text="If True, only staff/superusers can see this item. Regular users won't see it at all.")),
            ],
            options={
                'ordering': ['display_order', 'label'],
            },
        ),
    ]
