# Generated by Django 5.1.15 on 2026-01-06 22:17

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('postcode', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('country_code', django_countries.fields.CountryField(blank=True, db_index=True, max_length=2, null=True)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('company_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('company_website', models.URLField(blank=True, max_length=255, null=True)),
                ('primary_contact_title', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_contact_pronouns', models.CharField(blank=True, max_length=20, null=True)),
                ('primary_contact_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('primary_contact_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('secondary_contact_title', models.CharField(blank=True, max_length=100, null=True)),
                ('secondary_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('secondary_contact_pronouns', models.CharField(blank=True, max_length=20, null=True)),
                ('secondary_contact_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('secondary_contact_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('land_owner_title', models.CharField(blank=True, max_length=100, null=True)),
                ('land_owner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('land_owner_pronouns', models.CharField(blank=True, max_length=20, null=True)),
                ('land_owner_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('land_owner_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('land_owner_organization', models.CharField(blank=True, max_length=255, null=True)),
                ('land_owner_preferred_contact_method', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(db_index=True, decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(db_index=True, decimal_places=7, max_digits=11)),
                ('altitude', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('elevation', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('coordinate_system', models.CharField(default='WGS84', max_length=20)),
                ('what3w', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlantStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('queued', 'queued'), ('newly_planted', 'newly_planted'), ('teenage', 'teenage'), ('mature', 'mature'), ('landmark', 'landmark'), ('existing_dead', 'existing_dead'), ('death_drought', 'death_drought'), ('death_storm', 'death_storm'), ('death_flooding', 'death_flooding'), ('death_frost', 'death_frost'), ('death_snow', 'death_snow'), ('death_tornado', 'death_tornado'), ('death_windthrow', 'death_windthrow'), ('death_poor_soil', 'death_poor_soil'), ('death_failed_germinate', 'death_failed_germinate'), ('death_roots_unable', 'death_roots_unable'), ('death_competition', 'death_competition'), ('death_eaten_fauna', 'death_eaten_fauna'), ('death_insect_infest', 'death_insect_infest'), ('death_fungal_disease', 'death_fungal_disease'), ('death_large_animal', 'death_large_animal'), ('death_deforestation', 'death_deforestation'), ('death_wildfire', 'death_wildfire'), ('death_land_clearing', 'death_land_clearing'), ('death_vandalism', 'death_vandalism'), ('death_pollution', 'death_pollution'), ('death_unknown', 'death_unknown')], max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('emoji', models.CharField(max_length=10)),
                ('category', models.CharField(choices=[('queued', 'Queued for planting'), ('newly_planted', 'Newly planted tree'), ('teenage', 'Teenage tree'), ('mature', 'Mature tree'), ('landmark', 'Landmark/historical tree'), ('existing_dead', 'Existing dead tree'), ('death_drought', 'Killed by drought'), ('death_storm', 'Killed by storm'), ('death_flooding', 'Killed by flooding'), ('death_frost', 'Killed by frost'), ('death_snow', 'Killed by snow'), ('death_tornado', 'Tornado / hurricane damage'), ('death_windthrow', 'Windthrow / high wind stress'), ('death_poor_soil', 'Killed by poor soil conditions'), ('death_failed_germinate', 'Failed to germinate'), ('death_roots_unable', 'Roots unable to establish'), ('death_competition', 'Over competition from weeds/invasive plants'), ('death_eaten_fauna', 'Eaten by fauna (herbivores)'), ('death_insect_infest', 'Insect infestation'), ('death_fungal_disease', 'Fungal or bacterial disease'), ('death_large_animal', 'Large animal damage'), ('death_deforestation', 'Deforestation / logging'), ('death_wildfire', 'Wildfire'), ('death_land_clearing', 'Land clearing / agriculture expansion'), ('death_vandalism', 'Vandalism / trampling'), ('death_pollution', 'Pollution / acid rain'), ('death_unknown', 'Unknown cause of death')], max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_dead', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Plant Statuses',
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('cultivar', models.CharField(max_length=100)),
                ('common_name', models.CharField(blank=True, max_length=255, null=True)),
                ('scientific_name', models.CharField(blank=True, max_length=255, null=True)),
                ('hole_size_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('hole_depth_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('spacing_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'verbose_name_plural': 'Species',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('prospecting', 'Prospecting'), ('pending_approval', 'Pending Approval'), ('delayed', 'Delayed/Issue'), ('stopped', 'Stopped'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('archived_included', 'Archived (Stats Included)'), ('archived_excluded', 'Archived (Stats Excluded)')], max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('emoji', models.CharField(max_length=10)),
                ('is_archived', models.BooleanField(default=False)),
                ('includes_in_carbon', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Statuses',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('level', models.PositiveIntegerField(default=0, help_text='Lower number = more access')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.SlugField(max_length=100, unique=True)),
                ('item_type', models.CharField(choices=[('profile', 'Profile'), ('modal', 'Modal Trigger'), ('link', 'Link'), ('parent', 'Parent (has children)')], default='link', max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('icon', models.CharField(help_text='Bootstrap icon class or image path', max_length=100)),
                ('url_name', models.CharField(blank=True, help_text="Django URL name (e.g., 'projects:project_planner') or path", max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text="False = 'Coming Soon'")),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.navigationitem')),
                ('allowed_tiers', models.ManyToManyField(blank=True, help_text='Tiers that can access this item. Staff/superusers always have access.', related_name='accessible_nav_items', to='core.subscriptiontier')),
            ],
            options={
                'ordering': ['display_order', 'label'],
            },
        ),
    ]
