# Generated by Django 5.1.15 on 2026-01-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationitem',
            name='staff_only',
            field=models.BooleanField(default=False, help_text="If True, only staff/superusers can see this item. Regular users won't see it at all."),
        ),
    ]
