# Generated by Django 5.1.15 on 2026-01-12 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationitem',
            name='allowed_tiers',
            field=models.ManyToManyField(blank=True, help_text='Tiers that can access this item. Staff/superusers always have access.', related_name='accessible_nav_items', to='users.subscriptiontier'),
        ),
        migrations.AddField(
            model_name='navigationitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.navigationitem'),
        ),
    ]
