# Generated by Django 5.1.15 on 2026-01-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinate',
            name='coordinate_system',
            field=models.CharField(blank=True, default='WGS84', max_length=20),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='latitude',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='longitude',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=7, max_digits=11, null=True),
        ),
    ]
