# Generated by hand
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_coordinate_coordinate_system_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="navigationitem",
            name="is_footer",
            field=models.BooleanField(default=False, help_text="If True, render this nav item pinned to the bottom of the sidebar"),
        ),
    ]
