"""
Template tags for rendering form fields with Bootstrap styling.

These tags handle autogenerated field visibility automatically - if a field
has been removed from the form (e.g., in create mode), the entire field
block including label and help text won't render.
"""
from django import template
from django.utils.safestring import mark_safe

register = template.Library()


@register.simple_tag
def form_field(form, field_name, label=None, help_text=None, wrapper_class='mb-3'):
    """
    Render a form field with label and help text, only if it exists.

    Automatically handles autogenerated fields - if the field has been
    removed from the form, nothing is rendered.

    Usage:
        {% load form_tags %}
        {% form_field form 'area_hectares' %}
        {% form_field form 'name' label='Project Name' help_text='Enter name' %}
        {% form_field form 'email' wrapper_class='mb-3 col-md-6' %}

    Args:
        form: The form instance
        field_name: Name of the field to render
        label: Optional custom label (defaults to field's label)
        help_text: Optional custom help text (defaults to field's help_text)
        wrapper_class: CSS classes for the wrapper div (default: 'mb-3')

    Returns:
        Safe HTML string with the field, or empty string if field doesn't exist
    """
    # Check if field exists in form
    if field_name not in form.fields:
        return ''

    field = form[field_name]
    bound_field = form.fields[field_name]

    # Determine label
    field_label = label if label is not None else bound_field.label

    # Determine if field is required
    required_class = ' required' if bound_field.required else ''

    # Determine help text
    field_help = help_text if help_text is not None else bound_field.help_text

    # Build the HTML
    html_parts = [f'<div class="{wrapper_class}">']

    # Label
    if field_label:
        html_parts.append(
            f'<label for="id_{field_name}" class="form-label{required_class}">'
            f'{field_label}</label>'
        )

    # Field widget
    html_parts.append(str(field))

    # Help text
    if field_help:
        html_parts.append(f'<div class="form-text">{field_help}</div>')

    html_parts.append('</div>')

    return mark_safe('\n'.join(html_parts))


@register.simple_tag
def form_row(*args, **kwargs):
    """
    Render multiple form fields in a Bootstrap row.

    Usage:
        {% load form_tags %}
        {% form_row form 'first_name' 'last_name' %}
        {% form_row form 'city' 'state' 'zip_code' col_class='col-md-4' %}

    Args:
        form: The form instance (first positional arg)
        *field_names: Names of fields to render in the row
        col_class: CSS class for each column (default: auto-calculated)
        row_class: CSS class for the row (default: 'row')

    Returns:
        Safe HTML string with fields in a row, skipping non-existent fields
    """
    if len(args) < 2:
        return ''

    form = args[0]
    field_names = args[1:]

    row_class = kwargs.get('row_class', 'row')
    col_class = kwargs.get('col_class', None)

    # Filter to only fields that exist
    existing_fields = [name for name in field_names if name in form.fields]

    if not existing_fields:
        return ''

    # Auto-calculate column class if not provided
    if col_class is None:
        col_count = len(existing_fields)
        col_size = 12 // col_count
        col_class = f'col-md-{col_size}'

    html_parts = [f'<div class="{row_class}">']

    for field_name in existing_fields:
        field = form[field_name]
        bound_field = form.fields[field_name]

        required_class = ' required' if bound_field.required else ''

        html_parts.append(f'<div class="{col_class} mb-3">')

        if bound_field.label:
            html_parts.append(
                f'<label for="id_{field_name}" class="form-label{required_class}">'
                f'{bound_field.label}</label>'
            )

        html_parts.append(str(field))

        if bound_field.help_text:
            html_parts.append(f'<div class="form-text">{bound_field.help_text}</div>')

        html_parts.append('</div>')

    html_parts.append('</div>')

    return mark_safe('\n'.join(html_parts))
