from django.conf import settings
from django.db import models

from planting.models import Species


# =============================================================================
# SEED BATCH (Catalogued batch of seeds with QR code tracking and compliance)
# =============================================================================
class SeedBatch(models.Model):
    # Stratification status choices
    STRATIFICATION_NOT_REQUIRED = 'not_required'
    STRATIFICATION_IN_PROGRESS = 'in_progress'
    STRATIFICATION_COMPLETE = 'complete'

    STRATIFICATION_CHOICES = [
        (STRATIFICATION_NOT_REQUIRED, 'Not Required'),
        (STRATIFICATION_IN_PROGRESS, 'In Progress'),
        (STRATIFICATION_COMPLETE, 'Complete'),
    ]

    species = models.ForeignKey(Species, on_delete=models.PROTECT, related_name='seed_batches')
    qr_code = models.CharField(max_length=100, unique=True)
    batch_date = models.DateTimeField(db_index=True)

    # Supplier info
    supplier_name = models.CharField(max_length=255)
    supplier_contact = models.CharField(max_length=255, null=True, blank=True)

    # Compliance info (FRM - Forest Reproductive Material)
    compliance_type = models.CharField(max_length=100, default="Forest Reproductive Material (FRM)")
    nrid = models.CharField(max_length=50, null=True, blank=True)  # National Register ID
    ngr = models.CharField(max_length=50, null=True, blank=True)  # National Grid Reference
    basic_material = models.CharField(max_length=100, null=True, blank=True)
    master_certificate = models.CharField(max_length=100, null=True, blank=True)

    # Batch details
    weight_grams = models.DecimalField(max_digits=10, decimal_places=2)
    seed_count_estimate = models.IntegerField(null=True, blank=True)
    syringe_size_mm = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)

    # Stratification
    stratification_status = models.CharField(
        max_length=20,
        choices=STRATIFICATION_CHOICES,
        default=STRATIFICATION_NOT_REQUIRED
    )
    stratification_start_date = models.DateTimeField(null=True, blank=True)
    stratification_end_date = models.DateTimeField(null=True, blank=True)
    shelf_location = models.CharField(max_length=100, null=True, blank=True)

    # Quality testing
    quality_test_passed = models.BooleanField(default=False)
    quality_test_notes = models.TextField(null=True, blank=True)
    xray_embryo_tested = models.BooleanField(default=False)

    # Media & status
    photos = models.JSONField(default=list, blank=True)
    is_depleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = "Seed Batches"

    def __str__(self):
        return f"{self.qr_code} - {self.species.cultivar if self.species else 'Unknown'}"


# =============================================================================
# FUNGI BATCH (Catalogued batch of fungi with QR code tracking and compliance)
# =============================================================================
class FungiBatch(models.Model):
    species = models.ForeignKey(Species, on_delete=models.PROTECT, related_name='fungi_batches')
    qr_code = models.CharField(max_length=100, unique=True)
    batch_date = models.DateTimeField(db_index=True)
    supplier_name = models.CharField(max_length=255)
    supplier_contact = models.CharField(max_length=255, null=True, blank=True)
    quantity_ml = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    shelf_location = models.CharField(max_length=100, null=True, blank=True)
    quality_test_passed = models.BooleanField(default=False)
    quality_test_notes = models.TextField(null=True, blank=True)
    photos = models.JSONField(default=list, blank=True)
    is_depleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = "Fungi Batches"

    def __str__(self):
        return f"{self.qr_code} - {self.species.cultivar if self.species else 'Unknown'}"


# =============================================================================
# SPECIES MIX (AI-generated mix of species for a given location and goals)
# =============================================================================
class SpeciesMix(models.Model):
    """
    A user-owned species mix generated by the BLOOM AI agent.

    Stores the GPS location the mix was generated for, the environmental
    snapshot captured at generation time, user goal weights, and the
    AI-generated insights narrative.

    Data comes from: Species Mixer page (AI generation flow).
    Used by: Species Mixer, planting editor (future), reports.
    """
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='species_mixes',
    )
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)

    # GPS location the mix was generated for
    latitude = models.FloatField(null=True, blank=True)
    longitude = models.FloatField(null=True, blank=True)
    location_name = models.CharField(
        max_length=200,
        blank=True,
        help_text="Reverse-geocoded place name (e.g. 'Drumnadrochit, Scottish Highlands')"
    )

    # Environmental data snapshot cached at generation time
    # Keys: soil_ph, soil_texture, soil_moisture, mean_annual_rainfall_mm,
    #       mean_temp_c, climate_zone, flood_risk, water_body_nearby,
    #       native_species_observed (list)
    env_data = models.JSONField(
        default=dict,
        blank=True,
        help_text="Environmental data snapshot from SoilGrids, Met Office, EA/SEPA, NBN Atlas, GBIF"
    )

    # Candidate species cached from GBIF/iNaturalist/NBN Atlas queries during generation.
    # Used for fast Mode B re-scoring without repeating external API calls.
    cached_candidates = models.JSONField(
        default=list,
        blank=True,
        help_text="Candidate species from GBIF/iNaturalist/NBN Atlas (cached for rescore)"
    )

    # User-configurable mix size (overrides SPECIES_MIX_MAX_SPECIES setting)
    max_species = models.IntegerField(
        default=60,
        help_text="Maximum number of species to include in the final mix (1–200)"
    )

    # Goal weights (0–100)
    goal_erosion = models.IntegerField(default=50)
    goal_biodiversity = models.IntegerField(default=50)
    goal_pollinator = models.IntegerField(default=50)
    goal_carbon = models.IntegerField(default=50)
    goal_wildlife = models.IntegerField(default=50)

    # AI-generated text outputs
    ai_insights = models.TextField(
        blank=True,
        help_text="BLOOM-generated narrative: trade-off analysis and optimisation suggestions"
    )
    env_summary = models.CharField(
        max_length=500,
        blank=True,
        help_text="BLOOM-generated one-sentence environment summary"
    )

    # Generation metadata
    generation_model = models.CharField(max_length=100, default='bloom')
    generated_at = models.DateTimeField(null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-updated_at']
        verbose_name = "Species Mix"
        verbose_name_plural = "Species Mixes"

    def __str__(self):
        return f"{self.name} ({self.owner})"

    def goals_dict(self):
        """Return goal weights as a dict for passing to the AI agent."""
        return {
            'erosion_control': self.goal_erosion,
            'biodiversity': self.goal_biodiversity,
            'pollinator': self.goal_pollinator,
            'carbon_sequestration': self.goal_carbon,
            'wildlife_habitat': self.goal_wildlife,
        }


class SpeciesMixItem(models.Model):
    """
    A single species entry within a SpeciesMix.

    Tracks the AI-assigned ratio (proportion of this species in the mix),
    BLOOM's ecological justification, and user overrides.

    Data comes from: BLOOM agent output, then user adjustments in the mixer.
    """
    mix = models.ForeignKey(SpeciesMix, on_delete=models.CASCADE, related_name='items')
    species = models.ForeignKey(Species, on_delete=models.PROTECT, related_name='mix_items')

    # Proportion (0–1), AI-assigned then user-overridable
    ratio = models.FloatField(
        default=0.0,
        help_text="Proportion of this species in the mix (0–1, all items should sum to 1)"
    )

    # AI outputs
    ai_reason = models.TextField(
        blank=True,
        help_text="BLOOM's ecological justification for including this species"
    )
    suitability_score = models.FloatField(
        null=True,
        blank=True,
        help_text="AI-assigned suitability score for this species at this location (0–10)"
    )
    suitability_label = models.CharField(
        max_length=20,
        blank=True,
        help_text="Human-readable suitability: 'good', 'acceptable', or 'not_recommended'"
    )

    # User control
    is_active = models.BooleanField(
        default=True,
        help_text="User can deselect a species without deleting the record"
    )
    is_manual = models.BooleanField(
        default=False,
        help_text="True if this species was added manually by the user (not AI-generated)"
    )
    order = models.IntegerField(
        default=0,
        help_text="User-defined display order (drag to reorder)"
    )

    # Nativeness status — populated by GBIF distributions API at generation time
    uk_nativeness = models.CharField(
        max_length=20,
        blank=True,
        default='',
        choices=[
            ('native', 'Native'),
            ('naturalised', 'Naturalised'),
            ('introduced', 'Introduced'),
            ('unknown', 'Unknown'),
        ],
        help_text="UK nativeness status from GBIF distributions API"
    )

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['order', '-ratio']
        unique_together = [('mix', 'species')]

    def __str__(self):
        return f"{self.species} in {self.mix.name} ({self.ratio:.0%})"
