# Generated by Django 5.1.15 on 2026-01-06 22:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('calculation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('total_projects', models.IntegerField(default=0)),
                ('active_projects', models.IntegerField(default=0)),
                ('archived_projects', models.IntegerField(default=0)),
                ('total_sites', models.IntegerField(default=0)),
                ('active_sites', models.IntegerField(default=0)),
                ('archived_sites', models.IntegerField(default=0)),
                ('total_plants', models.BigIntegerField(default=0)),
                ('total_plants_alive', models.BigIntegerField(default=0)),
                ('total_plants_dead', models.BigIntegerField(default=0)),
                ('total_co2_sequestered_kg', models.BigIntegerField(default=0)),
                ('soil_co2_sequestered_kg', models.BigIntegerField(default=0)),
                ('plant_co2_sequestered_kg', models.BigIntegerField(default=0)),
                ('total_land_hectares', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('avg_global_health_index', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
            ],
            options={
                'verbose_name': 'Global Metrics',
                'verbose_name_plural': 'Global Metrics',
            },
        ),
        migrations.CreateModel(
            name='SiteSpeciesMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_planted', models.IntegerField(default=0)),
                ('total_alive', models.IntegerField(default=0)),
                ('total_dead', models.IntegerField(default=0)),
                ('survival_rate_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('avg_height_m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('avg_health_index', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('avg_age_days', models.IntegerField(blank=True, null=True)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species_metrics', to='projects.site')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_metrics', to='core.species')),
            ],
            options={
                'verbose_name_plural': 'Site Species Metrics',
                'indexes': [models.Index(fields=['site', 'survival_rate_percentage'], name='reports_sit_site_id_fc7cae_idx'), models.Index(fields=['species', 'survival_rate_percentage'], name='reports_sit_species_f99165_idx')],
                'unique_together': {('site', 'species')},
            },
        ),
    ]
