"""
Project creation wizard forms.

Each step is a separate file for clarity. This __init__.py ties them
together, defines the wizard order, and registers the wizard.

Template convention: projects/wizard_steps/create_project/{step_name}.html
"""
from django.contrib import messages

from core.wizard import BaseWizardView
from core.wizards import register_wizard
from projects.models import Project

from .basic_info import ProjectBasicInfoForm
from .environment import ProjectEnvironmentForm
from .address import ProjectAddressForm
from .coordinates import ProjectCoordinatesForm
from .contact import ProjectContactForm
from .summary import ProjectSummaryForm


class ProjectCreationWizard(BaseWizardView):
    """
    Project creation wizard.

    Creates Project with related Address, Contact, and optional
    Coordinate records through a multi-step wizard interface.
    """

    wizard_name = 'project_creation'
    success_url = '/projects/{slug}/'

    forms = [
        ProjectBasicInfoForm,
        ProjectEnvironmentForm,
        ProjectAddressForm,
        ProjectCoordinatesForm,
        ProjectContactForm,
        ProjectSummaryForm,
    ]

    def get_extra_create_data(self, request):
        """Set created_by to the current user when creating a project."""
        return {'created_by': request.user}

    def on_complete(self, request, all_data):
        """
        Create project and add success message for toast notification.

        Uses Django messages framework so the toast persists across
        the redirect to the project planner page.
        """
        # Call parent to create objects
        result = super().on_complete(request, all_data)

        if result.get('success'):
            # Add Django message - will be shown as toast on redirected page
            project_name = all_data.get('name', 'Project')
            messages.success(
                request,
                f'Successfully created project: {project_name}'
            )

        return result

    def get_form_kwargs(self, request, step):
        """
        Pass autogenerated_fields to forms so they're hidden in create mode.

        In create mode (edit_mode=False), auto-generated fields like
        area_hectares will be removed from the form entirely since
        they don't have values yet.
        """
        return {
            'autogenerated_fields': Project.AUTOGENERATED_FIELDS,
            'edit_mode': False,
        }

    def get_step_context(self, request, step, form):
        """Add extra context for specific steps using model constants."""
        context = {}

        # Environment step - soil and climate descriptions from model
        if step == 1:
            context['soil_descriptions'] = Project.SOIL_TYPE_DESCRIPTIONS
            context['climate_descriptions'] = Project.CLIMATE_DESCRIPTIONS

        # Coordinates step - help text from model
        if step == 3:
            context['coordinate_help'] = Project.COORDINATE_HELP

        return context


# Register the wizard
register_wizard('project_creation', ProjectCreationWizard)


# Export for convenience
__all__ = [
    'ProjectCreationWizard',
    'ProjectBasicInfoForm',
    'ProjectEnvironmentForm',
    'ProjectAddressForm',
    'ProjectCoordinatesForm',
    'ProjectContactForm',
    'ProjectSummaryForm',
]
