# Generated by Django 5.1.15 on 2026-01-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('queued', 'queued'), ('newly_planted', 'newly_planted'), ('teenage', 'teenage'), ('mature', 'mature'), ('landmark', 'landmark'), ('existing_dead', 'existing_dead'), ('death_drought', 'death_drought'), ('death_storm', 'death_storm'), ('death_flooding', 'death_flooding'), ('death_frost', 'death_frost'), ('death_snow', 'death_snow'), ('death_tornado', 'death_tornado'), ('death_windthrow', 'death_windthrow'), ('death_poor_soil', 'death_poor_soil'), ('death_failed_germinate', 'death_failed_germinate'), ('death_roots_unable', 'death_roots_unable'), ('death_competition', 'death_competition'), ('death_eaten_fauna', 'death_eaten_fauna'), ('death_insect_infest', 'death_insect_infest'), ('death_fungal_disease', 'death_fungal_disease'), ('death_large_animal', 'death_large_animal'), ('death_deforestation', 'death_deforestation'), ('death_wildfire', 'death_wildfire'), ('death_land_clearing', 'death_land_clearing'), ('death_vandalism', 'death_vandalism'), ('death_pollution', 'death_pollution'), ('death_unknown', 'death_unknown')], max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('emoji', models.CharField(max_length=10)),
                ('category', models.CharField(choices=[('queued', 'Queued for planting'), ('newly_planted', 'Newly planted tree'), ('teenage', 'Teenage tree'), ('mature', 'Mature tree'), ('landmark', 'Landmark/historical tree'), ('existing_dead', 'Existing dead tree'), ('death_drought', 'Killed by drought'), ('death_storm', 'Killed by storm'), ('death_flooding', 'Killed by flooding'), ('death_frost', 'Killed by frost'), ('death_snow', 'Killed by snow'), ('death_tornado', 'Tornado / hurricane damage'), ('death_windthrow', 'Windthrow / high wind stress'), ('death_poor_soil', 'Killed by poor soil conditions'), ('death_failed_germinate', 'Failed to germinate'), ('death_roots_unable', 'Roots unable to establish'), ('death_competition', 'Over competition from weeds/invasive plants'), ('death_eaten_fauna', 'Eaten by fauna (herbivores)'), ('death_insect_infest', 'Insect infestation'), ('death_fungal_disease', 'Fungal or bacterial disease'), ('death_large_animal', 'Large animal damage'), ('death_deforestation', 'Deforestation / logging'), ('death_wildfire', 'Wildfire'), ('death_land_clearing', 'Land clearing / agriculture expansion'), ('death_vandalism', 'Vandalism / trampling'), ('death_pollution', 'Pollution / acid rain'), ('death_unknown', 'Unknown cause of death')], max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_dead', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Plant Statuses',
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('cultivar', models.CharField(max_length=100)),
                ('common_name', models.CharField(blank=True, max_length=255, null=True)),
                ('scientific_name', models.CharField(blank=True, max_length=255, null=True)),
                ('hole_size_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('hole_depth_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('spacing_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'verbose_name_plural': 'Species',
            },
        ),
    ]
