# Generated by Django 5.1.15 on 2026-02-07 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ui_scale', models.FloatField(default=1.0, help_text='Editor UI scale multiplier (0.8-1.2)')),
                ('auto_topdown_drawing', models.BooleanField(default=True, help_text='Automatically set map to top-down view when using drawing tools')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='editor_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Editor Preferences',
                'verbose_name_plural': 'Editor Preferences',
            },
        ),
    ]
