# Generated by Django 5.1.15 on 2026-02-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planting', '0002_editorpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorpreferences',
            name='north_up_drawing',
            field=models.BooleanField(default=True, help_text='Rotate map to face North when entering top-down drawing mode'),
        ),
    ]
