# Generated by Django 5.1.15 on 2026-02-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planting', '0003_add_north_up_drawing'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='climate_zones',
            field=models.JSONField(blank=True, default=list, help_text="Accepted climate zones, e.g. ['temperate', 'continental']"),
        ),
        migrations.AddField(
            model_name='species',
            name='ecological_benefits',
            field=models.JSONField(blank=True, default=list, help_text="List of ecological benefits, e.g. ['pollinator', 'erosion_control', 'carbon_sequestration', 'wildlife_habitat', 'biodiversity']"),
        ),
        migrations.AddField(
            model_name='species',
            name='gbif_taxon_key',
            field=models.IntegerField(blank=True, help_text='GBIF taxon key for cross-referencing occurrence data', null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='max_annual_rainfall_mm',
            field=models.IntegerField(blank=True, help_text='Maximum annual rainfall (mm) this species can tolerate', null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='min_annual_rainfall_mm',
            field=models.IntegerField(blank=True, help_text='Minimum annual rainfall (mm) this species can tolerate', null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='min_temp_c',
            field=models.FloatField(blank=True, help_text='Minimum winter temperature tolerated (°C)', null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='native_regions',
            field=models.JSONField(blank=True, default=list, help_text="UK/EU regions where this species is native, e.g. ['scotland', 'england', 'wales', 'ireland']"),
        ),
        migrations.AddField(
            model_name='species',
            name='shade_tolerance',
            field=models.CharField(blank=True, choices=[('none', 'Full Sun'), ('partial', 'Partial Shade'), ('full', 'Full Shade')], help_text='Shade tolerance level', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='soil_moisture',
            field=models.CharField(blank=True, choices=[('dry', 'Dry'), ('moist', 'Moist'), ('wet', 'Wet'), ('variable', 'Variable')], help_text='Preferred soil moisture level', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='soil_ph_max',
            field=models.FloatField(blank=True, help_text='Maximum soil pH tolerated (e.g. 7.5)', null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='soil_ph_min',
            field=models.FloatField(blank=True, help_text='Minimum soil pH tolerated (e.g. 4.5)', null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='soil_types',
            field=models.JSONField(blank=True, default=list, help_text="List of accepted soil types, e.g. ['clay', 'loamy', 'peaty']"),
        ),
        migrations.AddField(
            model_name='species',
            name='typical_spacing_m',
            field=models.FloatField(blank=True, help_text='Typical planting spacing in metres (used by species mixer map visualisation)', null=True),
        ),
    ]
