# Generated by Django 5.1.15 on 2026-01-06 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FungiBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.CharField(max_length=100, unique=True)),
                ('batch_date', models.DateTimeField(db_index=True)),
                ('supplier_name', models.CharField(max_length=255)),
                ('supplier_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity_ml', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shelf_location', models.CharField(blank=True, max_length=100, null=True)),
                ('quality_test_passed', models.BooleanField(default=False)),
                ('quality_test_notes', models.TextField(blank=True, null=True)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('is_depleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fungi_batches', to='core.species')),
            ],
            options={
                'verbose_name_plural': 'Fungi Batches',
            },
        ),
        migrations.CreateModel(
            name='SeedBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.CharField(max_length=100, unique=True)),
                ('batch_date', models.DateTimeField(db_index=True)),
                ('supplier_name', models.CharField(max_length=255)),
                ('supplier_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('compliance_type', models.CharField(default='Forest Reproductive Material (FRM)', max_length=100)),
                ('nrid', models.CharField(blank=True, max_length=50, null=True)),
                ('ngr', models.CharField(blank=True, max_length=50, null=True)),
                ('basic_material', models.CharField(blank=True, max_length=100, null=True)),
                ('master_certificate', models.CharField(blank=True, max_length=100, null=True)),
                ('weight_grams', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seed_count_estimate', models.IntegerField(blank=True, null=True)),
                ('syringe_size_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('stratification_status', models.CharField(choices=[('not_required', 'Not Required'), ('in_progress', 'In Progress'), ('complete', 'Complete')], default='not_required', max_length=20)),
                ('stratification_start_date', models.DateTimeField(blank=True, null=True)),
                ('stratification_end_date', models.DateTimeField(blank=True, null=True)),
                ('shelf_location', models.CharField(blank=True, max_length=100, null=True)),
                ('quality_test_passed', models.BooleanField(default=False)),
                ('quality_test_notes', models.TextField(blank=True, null=True)),
                ('xray_embryo_tested', models.BooleanField(default=False)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('is_depleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seed_batches', to='core.species')),
            ],
            options={
                'verbose_name_plural': 'Seed Batches',
            },
        ),
    ]
