# Generated by Django 5.1.15 on 2026-01-05 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seed_catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('nickname', models.CharField(db_index=True, max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('total_flight_time_minutes', models.IntegerField(default=0)),
                ('avg_battery_life_minutes', models.IntegerField(blank=True, null=True)),
                ('last_maintenance', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DroneMaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('pass', 'Pass - No Issues'), ('advisory', 'Advisory - Recommend Attention'), ('fault', 'Fault - Requires Repair')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('advisory_notes', models.TextField(blank=True, null=True)),
                ('parts_replaced', models.TextField(blank=True, null=True)),
                ('next_maintenance_due', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DroneFlightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('flight_duration_minutes', models.IntegerField()),
                ('pathfinding_coordinates', models.JSONField(blank=True, default=list)),
                ('plants_planted', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flight_logs', to='drones.drone')),
                ('fungi_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flight_logs', to='seed_catalogue.fungibatch')),
                ('seed_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flight_logs', to='seed_catalogue.seedbatch')),
            ],
        ),
    ]
