# Generated by Django 5.1.15 on 2026-01-05 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('drones', '0001_initial'),
        ('projects', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='droneflightlog',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_logs', to='projects.site'),
        ),
        migrations.AddField(
            model_name='droneflightlog',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drone_flight_logs', to='core.species'),
        ),
        migrations.AddField(
            model_name='dronemaintenancelog',
            name='drone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='drones.drone'),
        ),
        migrations.AddField(
            model_name='dronemaintenancelog',
            name='performed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drone_maintenance_performed', to='users.user'),
        ),
        migrations.AddIndex(
            model_name='dronemaintenancelog',
            index=models.Index(fields=['drone', 'timestamp'], name='drones_dron_drone_i_0bf707_idx'),
        ),
        migrations.AddIndex(
            model_name='dronemaintenancelog',
            index=models.Index(fields=['drone', 'result'], name='drones_dron_drone_i_79e075_idx'),
        ),
    ]
