# Generated by Django 5.1.15 on 2026-01-12 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drones', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dronemaintenancelog',
            name='performed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drone_maintenance_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dronemaintenancelog',
            index=models.Index(fields=['drone', 'timestamp'], name='drones_dron_drone_i_0bf707_idx'),
        ),
        migrations.AddIndex(
            model_name='dronemaintenancelog',
            index=models.Index(fields=['drone', 'result'], name='drones_dron_drone_i_79e075_idx'),
        ),
    ]
