"""
Django settings for saas_platform project.

Generated by 'django-admin startproject' using Django 5.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url
if os.path.isfile('env.py'):
    import env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"

ALLOWED_HOSTS = [".herokuapp.com", "localhost", "127.0.0.1"]


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Required for allauth
    'cloudinary_storage',
    'cloudinary',
    # Third-party apps
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.apple',
    'django_countries',
    # Background task queue
    'django_dramatiq',
    # Local apps (order matters for dependencies)
    'core',
    'users',
    'planting',
    'species',
    'drones',
    'projects',
    'reports',
    'customers',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # Required for allauth
]

ROOT_URLCONF = 'saas_platform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.navigation_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'saas_platform.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': dj_database_url.config(default=os.environ.get("DATABASE_URL"))
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

ACCOUNT_EMAIL_VERIFICATION = 'none'

# Email backend - use console for development (prints to terminal)
# For production, configure SMTP settings
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Uncomment and configure for production:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.example.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
# EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
# DEFAULT_FROM_EMAIL = 'noreply@example.com'


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise settings for serving static files in production
STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# Cloudinary settings for media files (user uploads)
# CLOUDINARY_URL should be set in env.py and Heroku config vars
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =============================================================================
# CACHE (Redis in production, database cache in development)
# =============================================================================
REDIS_URL = os.environ.get('REDIS_URL', '')

def _redis_available(url):
    """Quick probe: attempt a socket connect to Redis, return bool."""
    if not url:
        return False
    import socket
    try:
        from urllib.parse import urlparse
        p = urlparse(url)
        host, port = p.hostname or 'localhost', p.port or 6379
        s = socket.create_connection((host, port), timeout=0.5)
        s.close()
        return True
    except OSError:
        return False

_REDIS_UP = _redis_available(REDIS_URL)

if _REDIS_UP:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
            'TIMEOUT': 60 * 60 * 24 * 30,  # 30 days
        }
    }
else:
    # No Redis — use the database as a cache store.
    # Run: python manage.py createcachetable   (once, to create the table)
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
            'LOCATION': 'django_cache',
            'TIMEOUT': 60 * 60 * 24,  # 1 day
        }
    }

# =============================================================================
# DRAMATIQ (Background task queue — Redis in production, stub in dev)
# =============================================================================
if _REDIS_UP:
    DRAMATIQ_BROKER = {
        'BROKER': 'dramatiq.brokers.redis.RedisBroker',
        'OPTIONS': {
            'url': REDIS_URL,
        },
        'MIDDLEWARE': [
            'dramatiq.middleware.AgeLimit',
            'dramatiq.middleware.TimeLimit',
            'dramatiq.middleware.Retries',
            'django_dramatiq.middleware.DbConnectionsMiddleware',
        ],
    }
else:
    # StubBroker: tasks registered but not queued.
    # In dev the api_views run generation synchronously instead.
    DRAMATIQ_BROKER = {
        'BROKER': 'dramatiq.brokers.stub.StubBroker',
        'OPTIONS': {},
        'MIDDLEWARE': [
            'dramatiq.middleware.AgeLimit',
            'dramatiq.middleware.TimeLimit',
            'dramatiq.middleware.Retries',
        ],
    }

# Expose whether async dispatch is available to application code
SPECIES_MIXER_ASYNC = _REDIS_UP

# =============================================================================
# SPECIES MIXER — AI (BLOOM via Hugging Face text-generation-inference)
# =============================================================================
# TGI server URL — run locally:
#   docker run -d --gpus all -p 8080:80 \
#     ghcr.io/huggingface/text-generation-inference:latest \
#     --model-id bigscience/bloomz-7b1-mt --max-total-tokens 4096
TGI_BASE_URL = os.environ.get('TGI_BASE_URL', 'http://localhost:8080')

# Maximum number of species to include in an AI-generated mix
SPECIES_MIX_MAX_SPECIES = int(os.environ.get('SPECIES_MIX_MAX_SPECIES', '60'))

# Custom user model
AUTH_USER_MODEL = 'users.User'

# Django-allauth settings
SITE_ID = 1
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of allauth
    'django.contrib.auth.backends.ModelBackend',
    # allauth specific authentication methods, such as login by email
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Allauth configuration (new format for v65+)
ACCOUNT_LOGIN_METHODS = {'email'}  # Login with email instead of username
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']  # Required signup fields
ACCOUNT_SESSION_REMEMBER = True

# Logging configuration - prints errors to console (visible in Heroku logs)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '[%(levelname)s] %(name)s: %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'ERROR',
        },
        # Environmental data APIs — DEBUG shows raw values, missing counts,
        # and parsed results so fetch issues can be diagnosed quickly.
        'species.services.environmental_data': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        # AI agent — INFO shows which path (TGI / rule-based) was taken.
        'species.services.ai_agent': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
