# Generated by Django 5.1.15 on 2026-02-22 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planting', '0004_species_climate_zones_species_ecological_benefits_and_more'),
        ('species', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciesMix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('location_name', models.CharField(blank=True, help_text="Reverse-geocoded place name (e.g. 'Drumnadrochit, Scottish Highlands')", max_length=200)),
                ('env_data', models.JSONField(blank=True, default=dict, help_text='Environmental data snapshot from SoilGrids, Met Office, EA/SEPA, NBN Atlas, GBIF')),
                ('cached_candidates', models.JSONField(blank=True, default=list, help_text='Candidate species returned by search_species_db during generation (cached for rescore)')),
                ('goal_erosion', models.IntegerField(default=50)),
                ('goal_biodiversity', models.IntegerField(default=50)),
                ('goal_pollinator', models.IntegerField(default=50)),
                ('goal_carbon', models.IntegerField(default=50)),
                ('goal_wildlife', models.IntegerField(default=50)),
                ('ai_insights', models.TextField(blank=True, help_text='BLOOM-generated narrative: trade-off analysis and optimisation suggestions')),
                ('env_summary', models.CharField(blank=True, help_text='BLOOM-generated one-sentence environment summary', max_length=500)),
                ('generation_model', models.CharField(default='bloom', max_length=100)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species_mixes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Species Mix',
                'verbose_name_plural': 'Species Mixes',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SpeciesMixItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio', models.FloatField(default=0.0, help_text='Proportion of this species in the mix (0–1, all items should sum to 1)')),
                ('ai_reason', models.TextField(blank=True, help_text="BLOOM's ecological justification for including this species")),
                ('suitability_score', models.FloatField(blank=True, help_text='AI-assigned suitability score for this species at this location (0–10)', null=True)),
                ('suitability_label', models.CharField(blank=True, help_text="Human-readable suitability: 'good', 'acceptable', or 'not_recommended'", max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='User can deselect a species without deleting the record')),
                ('is_manual', models.BooleanField(default=False, help_text='True if this species was added manually by the user (not AI-generated)')),
                ('order', models.IntegerField(default=0, help_text='User-defined display order (drag to reorder)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='species.speciesmix')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mix_items', to='planting.species')),
            ],
            options={
                'ordering': ['order', '-ratio'],
                'unique_together': {('mix', 'species')},
            },
        ),
    ]
