# Generated by Django 5.1.15 on 2026-03-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0002_speciesmix_speciesmixitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciesmix',
            name='max_species',
            field=models.IntegerField(default=60, help_text='Maximum number of species to include in the final mix (1–200)'),
        ),
        migrations.AlterField(
            model_name='speciesmix',
            name='cached_candidates',
            field=models.JSONField(blank=True, default=list, help_text='Candidate species from GBIF/iNaturalist/NBN Atlas (cached for rescore)'),
        ),
    ]
