# Generated by Django 5.1.15 on 2026-03-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0003_add_max_species_to_speciesmix'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciesmixitem',
            name='uk_nativeness',
            field=models.CharField(blank=True, choices=[('native', 'Native'), ('naturalised', 'Naturalised'), ('introduced', 'Introduced'), ('unknown', 'Unknown')], default='', help_text='UK nativeness status from GBIF distributions API', max_length=20),
        ),
    ]
