# Generated by Django 5.1.15 on 2026-03-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0004_add_uk_nativeness_to_speciesmixitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciesmix',
            name='is_published',
            field=models.BooleanField(default=False, help_text='True once the user has published this mix to the database'),
        ),
        migrations.AddField(
            model_name='speciesmix',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='When the mix was first published', null=True),
        ),
        migrations.AlterField(
            model_name='speciesmixitem',
            name='suitability_label',
            field=models.CharField(blank=True, help_text="Suitability label: 'excellent', 'good', 'fair', 'poor', or 'not_suitable'", max_length=20),
        ),
        migrations.AlterField(
            model_name='speciesmixitem',
            name='suitability_score',
            field=models.FloatField(blank=True, help_text='Suitability score 1–5 (5=excellent, 1=not suitable) for this species at this location', null=True),
        ),
    ]
